### ISSUE TITLE
Testing Matrix for chatting

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/chat.dataverse.org#12]
Today, I have created an account on the public homeserver https://chat.privacytools.io (one of the alternatives to matrix.org).

I used [this Medium.com article](https://medium.com/@agathver/staying-always-online-in-irc-using-riot-the-right-way-d4c4ff2f43d0) to join #dataverse on Freenode.

This is what the Riot desktop application looks like:
![grafik](https://user-images.githubusercontent.com/5468333/71817924-b4303d80-3087-11ea-891f-dd55752e3593.png)

At the same time, I have it open in my browser:
![grafik](https://user-images.githubusercontent.com/5468333/71817944-c4e0b380-3087-11ea-95f3-f101b352c6de.png)

What I really like: the Matrix bridge allows me to stay online and receive chatter that happens while I am not online. It's pretty intuitive compared to setting up your own IRC relay/bouncer/...

Let me mention there is a Slack bridge, too. Bots available for GitHub and Jenkins integrations.

**Comment by pdurbin** [comment]
I'm closing this because today I announced our move from IRC to Matrix: https://groups.google.com/g/dataverse-community/c/KU0FDNb8ckM/m/bO8ZXv2WAQAJ

I also updated the README: 7a2051b
