### ISSUE TITLE
public links to specific conversations

### ISSUE THREAD

**Issue by pdurbin** [IQSS/chat.dataverse.org#15]
Something we lost when moving from IRC to Matrix is public links to specific conversations.

For example, in IRC we started talking about Matrix in earnest here: http://irclog.iq.harvard.edu/dataverse/2021-05-26/#i_138097

<img width="1533" alt="Screen Shot 2022-12-03 at 1 00 49 PM" src="https://user-images.githubusercontent.com/21006/205455172-5f9c0679-6fd2-40c4-aae2-c9e1f7861274.png">

In Matrix, I can grab a link but you have to log in. Here's an example: https://matrix.to/#/!AmypvmJtUjBesRrnLM:matrix.org/$ylhOdQFhGNfaifhwDNtUYWfqApt_1S2nYZWR9Q1iYy8

<img width="792" alt="Screen Shot 2022-12-03 at 1 01 34 PM" src="https://user-images.githubusercontent.com/21006/205455202-560f6949-8e56-49b6-a7c7-1e6de9b867f4.png">

I imagine we'll want to open in issue at https://github.com/matrix-org/matrix-static

This seems related:

- https://github.com/matrix-org/matrix.to/issues/25

**Comment by pdurbin** [comment]
Good news! @MadLittleMods of Gitter fame has been hard at work on a new project called Matrix Public Archive (still a work in progress) that should give us nice public links to specific conversations. It looks like this:

<img width="1842" alt="Screen Shot 2022-12-03 at 12 59 38 PM" src="https://user-images.githubusercontent.com/21006/205455381-91b0e5bc-8895-4636-9ade-2b5c0801bc37.png">

That screenshot comes from [Matrix Live](https://matrix.org/matrixlive/) from October 14th: https://www.youtube.com/watch?v=UT6KSEqDUf8&t=548s

You can find a writeup here: https://matrix.org/blog/2022/08/05/this-week-in-matrix-2022-08-05#matrix-public-archive-website

In addition, just like the IRC days, we should be able to put a date in the URL to go directly to that date. (By the way a [jump to date](https://github.com/vector-im/element-web/issues/7677) feature is coming to Element.)

Eric and team seem very responsive. I just opened this issue last night and it was addressed right away:

- https://github.com/matrix-org/matrix-public-archive/issues/149

**Comment by pdurbin** [comment]
I started playing around with Matrix Public Archive and got it running locally. Here's day 1 of #dataverse on Matrix from http://localhost:3050/r/dataverse:matrix.org/date/2021/06/04 on my dev machine:

<img width="1257" alt="Screen Shot 2022-12-19 at 8 56 29 PM" src="https://user-images.githubusercontent.com/21006/208563122-06eb0150-1e90-4157-86da-4df9068f8cdf.png">

The "copy permalink" feature works differently than I expect. It links here, for example: https://matrix.to/#/!AmypvmJtUjBesRrnLM%3Amatrix.org/%24Jnp9yT6YITIhuoLG0q5q0tSK6XAvnPhVK1giiFEksMI

The way I would express what I want is here:

- https://github.com/matrix-org/matrix-public-archive/issues/146

That issue was closed in favor of this one, which seems to be the one to follow:

- https://github.com/matrix-org/matrix-public-archive/issues/137

That is, I'd like to have links to the archive site itself.

**Comment by MadLittleMods** [comment]
Keep in mind that the `Copy permalink` option will be disambiguated to `Copy matrix.to permalink`. This was already addressed in https://github.com/vector-im/hydrogen-web/pull/921#discussion_r1022138513

For linking to the archive itself, we will have https://github.com/matrix-org/matrix-public-archive/issues/137 and additionally there could be a `Copy permalink` menu option that links to the archive as you expect.

**Comment by pdurbin** [comment]
We've switched to Zulip, which allows public links to specific conversations. Works great. Closing.

For more on the switch:

- #22
